- hosts: all
  tasks: 
   - name: install httpd
     yum: name=httpd update_cache=yes state=latest
   - name: start httpd
     service:
      name: httpd
      state: started
   - name: Iptables flush filter
     ansible.builtin.iptables:
       chain: "{{ item }}"
       flush: yes
     with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
